version: '3.5'
name: filament-demo

services:
    adminer:
      image: adminer
      container_name: adminer
      ports:
        - 8099:8080

    db:
      image: mariadb:10.5.8
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: db_data_123
      ports:
        - 3307:3306

    laravel:
      container_name: laravel-app
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ../:/var/app
        - ./apache/:/etc/apache2/v-host/
      ports:
        - 80:80
